local AG=AleeGather
local spells,pending,lootContext={},nil,nil;local lootOpened=false
local function add(id,c)local n=GetSpellInfo(id);if n then spells[n]=c end end
local function tip()local f=_G.GameTooltipTextLeft1;local t=f and f:GetText();if t and AG:GetNodeIDByName(t)then return t end end
local function lc()local n=0;for i=1,((GetNumLootItems and GetNumLootItems())or 0)do local _,name,q=GetLootSlotInfo(i);if name and GetLootSlotLink(i)then n=n+math.max(1,tonumber(q)or 1)end end;return n end
local function finish()if not lootContext then return end;local n=lootContext.chat or 0;if n<1 then n=lootContext.expected or 1 end;AG:RecordSessionGather(lootContext.cat,lootContext.name,n);lootContext=nil end
function AG:InitializeCollector()add(2575,"Mining");add(2366,"Herb Gathering");add(33095,"Fishing");add(30427,"Extract Gas");add(8613,"Skinning");local f=CreateFrame("Frame");self.collector=f;for _,e in ipairs({"UNIT_SPELLCAST_SENT","UNIT_SPELLCAST_FAILED","UNIT_SPELLCAST_INTERRUPTED","LOOT_OPENED","LOOT_CLOSED","CHAT_MSG_LOOT","PLAYER_ENTERING_WORLD"})do f:RegisterEvent(e)end;f:SetScript("OnUpdate",function()if lootContext and lootContext.at and GetTime()>=lootContext.at then finish()end end);f:SetScript("OnEvent",function(_,e,...)
 if e=="UNIT_SPELLCAST_SENT"then local u,s,r,target=...;if u~="player"then return end;local c=spells[s];if not c then return end;local z,x,y=AG:GetPlayerPosition();if not z then return end;if c=="Skinning"then pending={id=590,name=target or AG:L("SKINNING"),cat=c,zone=z,x=x,y=y};lootOpened=false;return end;local name=target;if not name or not AG:GetNodeIDByName(name)then name=tip()end;local id=AG:GetNodeIDByName(name);local no=id and AG.Nodes[id];if not no or no.category~=c then pending=nil;return end;local off=(c=="Fishing"and 13)or(c=="Extract Gas"and 8)or 0;if off>0 and AG.ZoneSize[z]and GetPlayerFacing then local a=GetPlayerFacing();if a then local sz=AG.ZoneSize[z];x=x+math.sin(a)*off/sz[1];y=y-math.cos(a)*off/sz[2]end end;pending={id=id,name=name,cat=c,zone=z,x=x,y=y};lootOpened=false;if AG:ShouldLearnNode(z,c,id,x,y)then AG:SetLearnedState(z,id,x,y,false)end
 elseif e=="LOOT_OPENED"and pending then lootOpened=true;if lootContext then finish()end;lootContext={cat=pending.cat,name=pending.name,expected=lc(),chat=0};if AG:ShouldLearnNode(pending.zone,pending.cat,pending.id,pending.x,pending.y)then AG:AddLearnedNode(pending.id,pending.zone,pending.x,pending.y,"confirmed-loot")end;pending.confirmed=true
 elseif e=="CHAT_MSG_LOOT"and lootContext then local m=...;if m and string.find(m,"|Hitem:",1,true)then lootContext.chat=(lootContext.chat or 0)+(tonumber(string.match(m,"[xX](%d+)[^%d]*$"))or 1)end
 elseif e=="LOOT_CLOSED"then if pending and lootOpened and pending.confirmed and AG:ShouldLearnNode(pending.zone,pending.cat,pending.id,pending.x,pending.y)then AG:SetLearnedState(pending.zone,pending.id,pending.x,pending.y,true)end;if lootContext then lootContext.at=GetTime()+.35 end;pending=nil;lootOpened=false
 elseif e=="UNIT_SPELLCAST_FAILED"or e=="UNIT_SPELLCAST_INTERRUPTED"then local u=...;if u=="player"then pending=nil;lootOpened=false end
 elseif e=="PLAYER_ENTERING_WORLD"then pending=nil;lootContext=nil;lootOpened=false end end)end
